authors:
  vignemail1:
    name: "vignemail1"
    description: "system and network admin"
    avatar: 'https://avatar.iran.liara.run/public/job/police/male'
    slug: vignemail1
    # url: url            # Author website URL