---
name: Build and Publish MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow on push to this branch
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger the workflow when a PR is opened, synchronized or reopened

permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # The GitHub Actions runner to use

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Enable checking out submodules
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and publish the MkDocs site
        run: mkdocs gh-deploy --force