---
name: Build and Publish MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow on push to this branch
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger the workflow when a PR is opened, synchronized or reopened

jobs:
  build-and-publish:
    runs-on: ubuntu-latest  # The GitHub Actions runner to use

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Enable checking out submodules

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9  # The version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # The GitHub token for authentication
          publish_dir: ./site